# Generated by Django 5.1.2 on 2026-03-05 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('invoice_number', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=255)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('bank_account', models.CharField(blank=True, default='', max_length=64)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('extracted_json', models.JSONField(blank=True, default=dict)),
                ('ocr_confidence', models.FloatField(default=0)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('risk_label', models.CharField(default='unknown', max_length=20)),
                ('fraud_reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='invoice_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoices')),
            ],
        ),
    ]
