# Generated by Django 5.1.2 on 2026-03-05 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blockchain_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(blank=True, default='', max_length=255)),
                ('invoice_hash', models.CharField(blank=True, default='', max_length=255)),
                ('network', models.CharField(default='ethereum', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_records', to='invoices.invoices')),
            ],
        ),
    ]
