# Generated by Django 5.1.2 on 2026-03-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_blockchain_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='guest_session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='username',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
    ]
