# Generated by Django 5.1.2 on 2026-03-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoices_guest_session_id_alter_invoices_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('total_invoices', models.IntegerField(default=0)),
                ('total_amount_processed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('average_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_invoice_date', models.DateField(blank=True, null=True)),
                ('risk_score', models.FloatField(default=50.0)),
                ('is_trusted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('username', 'name')},
            },
        ),
    ]
