# -*- coding: utf-8 -*-
"""model-training2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zj0vzepCQYduyTlF2t9TbezWX22ZprSf
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

df = pd.read_csv("invoice_fraud_detection.csv")

print(df.head())
print("\nDataset Shape:", df.shape)

drop_columns = [
    "invoice_id",
    "invoice_number",
    "vendor_id",
    "purchase_order_number"
]

df = df.drop(drop_columns, errors="ignore")

df["invoice_date"] = pd.to_datetime(df["invoice_date"])
df["due_date"] = pd.to_datetime(df["due_date"])

df["invoice_day"] = df["invoice_date"].dt.day
df["invoice_month"] = df["invoice_date"].dt.month
df["invoice_year"] = df["invoice_date"].dt.year

df["due_day"] = df["due_date"].dt.day
df["due_month"] = df["due_date"].dt.month

df = df.drop(["invoice_date", "due_date"], axis=1)

df = pd.get_dummies(df, drop_first=True)

X = df.drop("fraud_label", axis=1)
y = df["fraud_label"]

print("Feature Matrix Shape:", X.shape)
print("Target Vector Shape:", y.shape)

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)

logic_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=700))
])

from sklearn.model_selection import cross_val_score

logic_scores = cross_val_score(
    logic_pipeline,
    X,
    y,
    cv=skf,
    scoring="accuracy"
)

print("Logistic Regression CV Scores:")
print(logic_scores)

print("Mean Accuracy:", logic_scores.mean())

from sklearn.model_selection import cross_val_predict
from sklearn.metrics import classification_report, confusion_matrix

y_pred_logic = cross_val_predict(
    logic_pipeline,
    X,
    y,
    cv=skf
)

print("\nLogistic Regression Classification Report:")
print(classification_report(y, y_pred_logic))

print("\nConfusion Matrix:")
print(confusion_matrix(y, y_pred_logic))

rf_model = RandomForestClassifier(
    n_estimators=500,
    max_depth=15,
    random_state=42,
    n_jobs=-1
)

rf_scores = cross_val_score(
    rf_model,
    X,
    y,
    cv=skf,
    scoring="accuracy"
)

print("\nRandom Forest CV Scores:")
print(rf_scores)

print("Mean Accuracy:", rf_scores.mean())

y_pred_rf = cross_val_predict(
    rf_model,
    X,
    y,
    cv=skf
)

print("\nRandom Forest Classification Report:")
print(classification_report(y, y_pred_rf))

print("\nConfusion Matrix:")
print(confusion_matrix(y, y_pred_rf))

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
import joblib

df_original = pd.read_csv("invoice_fraud_detection.csv")

df_original = df_original.drop(drop_columns, errors="ignore")

df_original["invoice_date"] = pd.to_datetime(df_original["invoice_date"])
df_original["due_date"] = pd.to_datetime(df_original["due_date"])

df_original["invoice_day"] = df_original["invoice_date"].dt.day
df_original["invoice_month"] = df_original["invoice_date"].dt.month
df_original["invoice_year"] = df_original["invoice_date"].dt.year

df_original["due_day"] = df_original["due_date"].dt.day
df_original["due_month"] = df_original["due_date"].dt.month

df_original = df_original.drop(["invoice_date","due_date"], axis=1)

X_final = df_original.drop("fraud_label", axis=1)
y_final = df_original["fraud_label"]

categorical_cols = X_final.select_dtypes(include=["object"]).columns
numeric_cols = X_final.select_dtypes(include=["int64","float64"]).columns

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
        ("num", "passthrough", numeric_cols)
    ]
)

final_model = Pipeline([
    ("preprocessing", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=500,
        max_depth=15,
        random_state=42,
        n_jobs=-1
    ))
])


final_model.fit(X_final, y_final)

print("Final pipeline trained successfully")

joblib.dump(final_model, "invoice_fraud_model.pkl")

print("Pickle model saved: invoice_fraud_model.pkl")

import joblib

model = joblib.load("invoice_fraud_model.pkl")

print(type(model))