# Generated by Django 5.1.2 on 2026-03-05 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercustom',
            name='lst_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
