# Generated by Django 5.1.2 on 2026-03-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fraud_analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('invoice_id', models.IntegerField(blank=True, null=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=100)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=255)),
                ('risk_score', models.FloatField(default=0)),
                ('risk_label', models.CharField(default='low', max_length=20)),
                ('is_fraud', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, default='')),
                ('model_version', models.CharField(default='demo-rule-v1', max_length=50)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
