"""
Django settings for InvGuard project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
from urllib.parse import parse_qs, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(env_path):
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


_load_env_file(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z995+lwhy-q)u2+=r*qsclpv6%!qio5l(3$@s7#3orr#0#*2&9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['16.171.152.233']


# Application definition

INSTALLED_APPS = [
    'auth1',
    'jazzmin',
    'subscriptions',
    'invoices',
    'fraud_detection',
    'home',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'auth1.middleware.GuestSessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'InvGuard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'InvGuard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
SERVICE_URL = os.getenv("SERVICE_URL") or os.getenv("DATABASE_URL")
parsed_service_url = urlparse(SERVICE_URL) if SERVICE_URL else None
service_query = parse_qs(parsed_service_url.query) if parsed_service_url else {}

DB_ENGINE = os.getenv("DB_ENGINE", "django.db.backends.postgresql")
DB_NAME = (
    os.getenv("DB_NAME")
    or os.getenv("PGDATABASE")
    or os.getenv("dbname")
    or (parsed_service_url.path.lstrip("/") if parsed_service_url else None)
)
DB_USER = (
    os.getenv("DB_USER")
    or os.getenv("PGUSER")
    or os.getenv("user")
    or (parsed_service_url.username if parsed_service_url else None)
)
DB_PASSWORD = (
    os.getenv("DB_PASSWORD")
    or os.getenv("PGPASSWORD")
    or os.getenv("password")
    or (parsed_service_url.password if parsed_service_url else None)
)
DB_HOST = (
    os.getenv("DB_HOST")
    or os.getenv("PGHOST")
    or os.getenv("host")
    or (parsed_service_url.hostname if parsed_service_url else None)
)
DB_PORT = (
    os.getenv("DB_PORT")
    or os.getenv("PGPORT")
    or os.getenv("port")
    or (str(parsed_service_url.port) if parsed_service_url and parsed_service_url.port else None)
    or "5432"
)
DB_SSLMODE = (
    os.getenv("DB_SSLMODE")
    or (service_query.get("sslmode", [None])[0] if service_query else None)
    or "require"
)

missing_db_values = []
if not DB_NAME:
    missing_db_values.append("DB_NAME or PGDATABASE")
if not DB_USER:
    missing_db_values.append("DB_USER or PGUSER")
if not DB_PASSWORD:
    missing_db_values.append("DB_PASSWORD or PGPASSWORD")
if not DB_HOST:
    missing_db_values.append("DB_HOST or PGHOST")

if missing_db_values:
    raise ImproperlyConfigured(
        "Missing PostgreSQL environment variables: " + ", ".join(missing_db_values)
    )

DATABASES = {
    "default": {
        "ENGINE": DB_ENGINE,
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASSWORD,
        "HOST": DB_HOST,
        "PORT": DB_PORT,
        "OPTIONS": {
            "sslmode": DB_SSLMODE,
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

PK_KEY = os.getenv("PK_KEY", "")
SK_KEY = os.getenv("SK_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")
DOMAIN = os.getenv("DOMAIN", "http://127.0.0.1:8000")
STRIPE_REQUEST_TIMEOUT_SECONDS = os.getenv("STRIPE_REQUEST_TIMEOUT_SECONDS", "12")
STRIPE_CHECKOUT_RETRY_COUNT = os.getenv("STRIPE_CHECKOUT_RETRY_COUNT", "1")
STRIPE_PAYMENT_METHOD_TYPES = [
    item.strip()
    for item in os.getenv("STRIPE_PAYMENT_METHOD_TYPES", "card").split(",")
    if item.strip()
]
FRAUD_MODEL_PICKLE_PATH = os.getenv(
    "FRAUD_MODEL_PICKLE_PATH",
    str(BASE_DIR / "fraud_detection" / "model" / "fraud_model.pkl"),
)

# Blockchain settings
GANACHE_URL = os.getenv("GANACHE_URL", "http://127.0.0.1:7545")
BLOCKCHAIN_RPC_URL = os.getenv("BLOCKCHAIN_RPC_URL", GANACHE_URL)
BLOCKCHAIN_CONTRACT_ADDRESS = os.getenv("BLOCKCHAIN_CONTRACT_ADDRESS", "")
BLOCKCHAIN_SIGNER_PRIVATE_KEY = os.getenv("BLOCKCHAIN_SIGNER_PRIVATE_KEY", "")
BLOCKCHAIN_PRIORITY_FEE_GWEI = os.getenv("BLOCKCHAIN_PRIORITY_FEE_GWEI", "2")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security Headers & Django-Ratelimit Caching support
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'rate-limit-cache',
    }
}
