# Generated by Django 5.1.2 on 2026-03-05 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('subscription_type', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('autopay', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='inr', max_length=10)),
                ('plan_limit', models.CharField(blank=True, default='', max_length=50)),
                ('payment_method', models.CharField(default='pending', max_length=50)),
                ('stripe_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_customer_email', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'db_table': 'user_subscription',
            },
        ),
    ]
